In [1]:
import numpy as np


#### 1. **Create an array of 10 zeros**


In [2]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2. **Create an array of 10 ones**



In [3]:
b = np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 3. **Create an array of 10 fives**



In [5]:
c = np.full(10 , 5)
c

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### 4. **Create a NumPy array of integers from 1 to 10**



In [6]:
arr = np.arange(1, 11)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### 5. **Create a 3x3 identity matrix**



In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 6. **Create a 2D array with values ranging from 1 to 6**



In [11]:
arr = np.arange(1, 7).reshape(2, 3)
arr

array([[1, 2, 3],
       [4, 5, 6]])

#### 7. **Create an array filled with zeros**



In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

#### 8. **Create a 3x3 array filled with 25**



In [16]:
arr = np.full((3,3) , 25)
arr

array([[25, 25, 25],
       [25, 25, 25],
       [25, 25, 25]])

#### 9. **Create an array of random numbers between 0 and 1**


In [17]:
np.random.random(5)

array([0.34646361, 0.29813221, 0.46087126, 0.0531147 , 0.37839441])


#### 10. **Create an array of random integers between 1 and 100, with a shape of (3, 6)**


In [19]:
np.random.randint(1,100 , size=(3,6))

array([[81, 66, 66, 95,  8,  6],
       [10,  3, 63, 41, 89, 53],
       [61, 38, 73, 70, 94,  7]])


#### 11. **Create an array of linearly spaced numbers between 0 and 1, with 5 elements**


In [20]:
arr = np.linspace(0, 1, 5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])


#### 12. **Create a random 3x4 array using NumPy**



In [22]:
np.random.randint(1,30 , size=(3,4))

array([[ 6, 11, 16, 12],
       [ 6, 15,  6, 19],
       [15, 13, 16, 25]])

#### 13. **Create an array of 3x3 random integers between 0 and 50**



In [23]:
np.random.randint(0,50 , size=(3,3))

array([[ 1, 33,  3],
       [42,  7, 48],
       [24, 41,  9]])

#### 14. **Create a diagonal matrix from the array [1, 2, 3, 4]**


In [24]:
arr = np.array([1, 2, 3, 4])
dm = np.diag(arr)
dm


array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])


#### 15. **Create an array of 10 random floats between 1 and 100**

In [26]:
array_1d = np.random.uniform(1,100 ,10)
array_1d

array([82.88965336, 97.96465005, 36.73157111, 86.12580049, 40.0678977 ,
       83.48482892, 41.0093893 , 52.68143303, 68.18135423, 84.61690031])

 ### 16.Add 10 to each element of the array a = np.array([1, 2, 3, 4, 5])

In [28]:
a = np.array([1, 2, 3, 4, 5])
c = a + 10
c

array([11, 12, 13, 14, 15])

###  17.Perform integer division of each element of the array(Create an array of 10 random floats) a  by 2

In [31]:
c = np.random.random(10)
b = c /2 
b


array([0.37744652, 0.16127689, 0.44895983, 0.30464936, 0.31927388,
       0.08500874, 0.06030425, 0.44224934, 0.41897532, 0.301559  ])