In [1]:
import numpy as np


#### 1. **Write a NumPy code to reshape a 1D array of size 12 into a 2x6 array.**




In [21]:
a = np.arange(12)
b = a.reshape(2, 6)
b


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

#### 2. **Write a NumPy code to stack two arrays `arr1 = [1, 2, 3]` and `arr2 = [4, 5, 6]` vertically.**




In [2]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

x = np.vstack((arr1, arr2))
x


array([[1, 2, 3],
       [4, 5, 6]])

#### 3. **Write a NumPy code to shuffle the elements of a list `arr = [1, 2, 3, 4, 5]` in place using `random.shuffle()`.**


In [14]:
import random
b = [1, 2, 3, 4, 5]
random.shuffle(b)
b

[2, 3, 5, 1, 4]


#### 4. **Write a NumPy code to create a copy of the array `arr = [1, 2, 3]` using `b.copy()` and modify the copy.**


In [15]:
b = [1, 2, 3]
b.copy
b

[1, 2, 3]


#### 5. **Write a NumPy code to flatten a 2D array `arr = [[1, 2], [3, 4]]` into a 1D array.**


In [23]:
b = np.array([[1, 2], [3, 4]])
x = b.flatten()
x

array([1, 2, 3, 4])


#### 6. **Write a NumPy code to create a 3x3 matrix with random integers between 1 and 10.**


In [26]:
x = np.random.randint(1,10 ,size =(3,3))
x

array([[9, 5, 9],
       [4, 4, 2],
       [7, 7, 8]])


#### 7. **Write a NumPy code to calculate the sum of all elements in a 3x3 matrix.**


In [28]:
result = np.sum(x)
result

np.int32(55)


#### 8. **Write a NumPy code to create a 3D array of shape `(3, 2, 4)` and calculate the sum along the second axis.**



In [36]:
arr = np.arange(24).reshape(3, 2, 4) #2*3*4 = 24 

sum = np.sum(arr, axis=1)

print("Original array:\n", arr)
print("\nSum along axis 1:\n", sum)


Original array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]

Sum along axis 1:
 [[ 4  6  8 10]
 [20 22 24 26]
 [36 38 40 42]]


#### 9. **Write a NumPy code to create an array of integers from 10 to 50 and select all even numbers.**


In [38]:
arr = np.arange(10, 50)
x = arr[arr % 2 == 0]
x

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])


#### 10. **Write a NumPy code to create a 1D array and find the maximum, minimum, mean, and standard deviation of its elements.**


In [8]:
arr = np.random.randint(1, 4, 8)
arr
arr.max()
#arr.min()
#arr.mean()
#arr.std()

np.int32(3)


#### 11. **Write a NumPy code to calculate the dot product of two arrays `a = np.array([1, 2])` and `b = np.array([3, 4])`.**


In [9]:
a = np.array([1, 2])
b = np.array([3, 4])

product = np.dot(a, b)

product


np.int32(11)


#### 12. **Write a NumPy code to slice a 2D array and retrieve all elements from the second row.**



In [12]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

r2 = arr[1]
r2


array([4, 5, 6])

#### 13. **Write a NumPy code to slice a 1D array and retrieve elements from index 2 to 4.**


In [15]:
arr = np.array([12, 21, 33, 12, 43, 12, 43])

result = arr[2:4]

result


array([33, 12])


#### 14. **Write a NumPy code to reshape a 1D array into a 2D array of shape (2, 3) and flatten it back to 1D.**



In [23]:
arr = np.array([1, 2, 3, 4 ,7, 8])
x = arr.reshape((2, 3))
x

array([[1, 2, 3],
       [4, 7, 8]])

#### 15. **Write a NumPy code to generate an array of 10 random integers between 1 and 100.**

In [26]:
np.random.randint(1,100,10)

array([60, 75, 88, 41, 54, 25, 50, 55, 46, 95])